"use client"

import * as React from "react"
import { ChevronRight, File, Folder, Copy, Download, ExternalLink } from "lucide-react"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible"

// Sample file structure with content
const fileStructure: Record<string, FileNode> = {
  app: {
    type: "folder" as const,
    children: {
      "page.tsx": {
        type: "file" as const,
        content: `import { Metadata } from 'next'
import { Hero } from '@/components/hero'
import { Features } from '@/components/features'

export const metadata: Metadata = {
  title: 'Home - My App',
  description: 'Welcome to my application',
}

export default function HomePage() {
  return (
    <main className="min-h-screen">
      <Hero />
      <Features />
    </main>
  )
}`,
      },
      "layout.tsx": {
        type: "file" as const,
        content: `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`,
      },
      "globals.css": {
        type: "file" as const,
        content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}`,
      },
    },
  },
  components: {
    type: "folder" as const,
    children: {
      "architecture-animation.tsx": {
        type: "file" as const,
        content: `"use client"

import { useState, useEffect, useRef } from "react"
import { Monitor, Server, Database, Shield, Sparkles, Zap } from 'lucide-react'

interface Particle {
  id: number
  x: number
  y: number
  vx: number
  vy: number
  size: number
  color: string
  opacity: number
  life: number
  maxLife: number
}

interface ComponentNode {
  id: string
  title: string
  icon: any
  x: number
  y: number
  targetX: number
  targetY: number
  scale: number
  opacity: number
  connectionCount: number
}`,
      },
      "hero.tsx": {
        type: "file" as const,
        content: `import { Button } from "@/components/ui/button"
import { ArrowRight } from 'lucide-react'

export function Hero() {
  return (
    <section className="py-20 px-4">
      <div className="container mx-auto text-center">
        <h1 className="text-4xl md:text-6xl font-bold mb-6">
          Build Amazing Apps
        </h1>
        <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
          Create beautiful, responsive applications with modern tools and best practices.
        </p>
        <Button size="lg" className="gap-2">
          Get Started
          <ArrowRight className="w-4 h-4" />
        </Button>
      </div>
    </section>
  )
}`,
      },
      "features.tsx": {
        type: "file" as const,
        content: `import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Zap, Shield, Sparkles } from 'lucide-react'

const features = [
  {
    title: "Fast Performance",
    description: "Optimized for speed and efficiency",
    icon: Zap,
  },
  {
    title: "Secure by Default",
    description: "Built with security best practices",
    icon: Shield,
  },
  {
    title: "Modern Design",
    description: "Beautiful and intuitive user interface",
    icon: Sparkles,
  },
]

export function Features() {
  return (
    <section className="py-20 px-4">
      <div className="container mx-auto">
        <h2 className="text-3xl font-bold text-center mb-12">Features</h2>
        <div className="grid md:grid-cols-3 gap-6">
          {features.map((feature) => (
            <Card key={feature.title}>
              <CardHeader>
                <feature.icon className="w-8 h-8 mb-2" />
                <CardTitle>{feature.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription>{feature.description}</CardDescription>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  )
}`,
      },
    },
  },
}

interface FileNode {
  type: "file" | "folder"
  content?: string
  children?: Record<string, FileNode>
}

export default function FileExplorer() {
  const [selectedFile, setSelectedFile] = React.useState<string>("components/architecture-animation.tsx")
  const [selectedContent, setSelectedContent] = React.useState<string>("")

  React.useEffect(() => {
    // Get content for selected file
    const pathParts = selectedFile.split("/")
    let current: any = fileStructure

    for (const part of pathParts) {
      if (current[part]) {
        current = current[part]
      }
    }

    if (current?.content) {
      setSelectedContent(current.content)
    }
  }, [selectedFile])

  const renderFileTree = (node: Record<string, FileNode>, path = "") => {
    return Object.entries(node).map(([name, item]) => {
      const fullPath = path ? `${path}/${name}` : name

      if (item.type === "folder") {
        return (
          <FileTreeFolder key={fullPath} name={name} path={fullPath}>
            {item.children && renderFileTree(item.children, fullPath)}
          </FileTreeFolder>
        )
      }

      return (
        <FileTreeFile
          key={fullPath}
          name={name}
          path={fullPath}
          isSelected={selectedFile === fullPath}
          onClick={() => setSelectedFile(fullPath)}
        />
      )
    })
  }

  const getFileExtension = (filename: string) => {
    return filename.split(".").pop() || ""
  }

  const getBreadcrumbs = () => {
    return selectedFile.split("/")
  }

  return (
    <div className="h-full bg-black text-white flex">
      {/* File Explorer Sidebar */}
      <div className="w-64 bg-black border-r border-white/20 flex flex-col">
        <div className="p-3 border-b border-white/20">
          <h2 className="text-sm font-medium text-white tracking-wider">EXPLORER</h2>
        </div>
        <ScrollArea className="flex-1">
          <div className="p-2">{renderFileTree(fileStructure)}</div>
        </ScrollArea>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col">
        {/* Breadcrumb Header */}
        <div className="h-12 bg-black border-b border-white/20 flex items-center px-4 justify-between">
          <div className="flex items-center gap-2 text-sm text-white/80">
            {getBreadcrumbs().map((crumb, index) => (
              <React.Fragment key={index}>
                {index > 0 && <ChevronRight className="w-3 h-3 text-white/60" />}
                <span className={index === getBreadcrumbs().length - 1 ? "text-white font-medium" : "text-white/60"}>{crumb}</span>
              </React.Fragment>
            ))}
          </div>
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="icon" className="w-8 h-8 text-white/60 hover:text-white hover:bg-white/10 border border-transparent hover:border-white/30 transition-all duration-200">
              <Copy className="w-4 h-4" />
            </Button>
            <Button variant="ghost" size="icon" className="w-8 h-8 text-white/60 hover:text-white hover:bg-white/10 border border-transparent hover:border-white/30 transition-all duration-200">
              <Download className="w-4 h-4" />
            </Button>
            <Button variant="ghost" size="icon" className="w-8 h-8 text-white/60 hover:text-white hover:bg-white/10 border border-transparent hover:border-white/30 transition-all duration-200">
              <ExternalLink className="w-4 h-4" />
            </Button>
          </div>
        </div>

        {/* Code Editor Area */}
        <div className="flex-1 relative overflow-hidden">
          <ScrollArea className="h-full">
            <div className="flex">
              {/* Line Numbers */}
              <div className="bg-black px-4 py-4 text-white/40 text-sm font-mono select-none border-r border-white/10 min-w-[60px]">
                {selectedContent.split("\n").map((_, index) => (
                  <div key={index} className="leading-6 text-right hover:text-white/80 transition-colors duration-200">
                    {index + 1}
                  </div>
                ))}
              </div>

              {/* Code Content */}
              <div className="flex-1 bg-black p-4">
                <pre className="text-sm font-mono leading-6 text-white/90">
                  <code
                    dangerouslySetInnerHTML={{
                      __html: highlightCode(selectedContent, getFileExtension(selectedFile.split("/").pop() || "")),
                    }}
                  />
                </pre>
              </div>
            </div>
          </ScrollArea>
        </div>
      </div>
    </div>
  )
}

function FileTreeFolder({
  name,
  path,
  children,
}: {
  name: string
  path: string
  children: React.ReactNode
}) {
  const [isOpen, setIsOpen] = React.useState(path === "components" || path === "app")

  return (
    <div className="mb-1">
      <Collapsible open={isOpen} onOpenChange={setIsOpen}>
        <CollapsibleTrigger asChild>
          <Button
            variant="ghost"
            className="w-full justify-start h-8 px-2 text-white/80 hover:bg-white/10 hover:text-white font-normal border border-transparent hover:border-white/20 transition-all duration-200 rounded-lg"
          >
            <ChevronRight className={`w-4 h-4 mr-2 transition-transform duration-200 ${isOpen ? "rotate-90 text-white" : "text-white/60"}`} />
            <Folder className="w-4 h-4 mr-2 text-blue-400" />
            <span className="text-sm">{name}</span>
          </Button>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="ml-4 border-l border-white/10 pl-2">{children}</div>
        </CollapsibleContent>
      </Collapsible>
    </div>
  )
}

function FileTreeFile({
  name,
  path,
  isSelected,
  onClick,
}: {
  name: string
  path: string
  isSelected: boolean
  onClick: () => void
}) {
  const getFileIcon = (filename: string) => {
    const ext = filename.split(".").pop()
    switch (ext) {
      case "tsx":
      case "ts":
        return "#3b82f6" // blue-500
      case "css":
        return "#06b6d4" // cyan-500
      case "json":
        return "#f59e0b" // amber-500
      default:
        return "#9ca3af" // gray-400
    }
  }

  return (
    <Button
      variant="ghost"
      className={`w-full justify-start h-8 px-2 mb-1 font-normal transition-all duration-200 rounded-lg border ${
        isSelected 
          ? "bg-white/20 text-white border-white/40" 
          : "text-white/80 hover:bg-white/10 hover:text-white border-transparent hover:border-white/20"
      }`}
      onClick={onClick}
    >
      <File className="w-4 h-4 mr-2 flex-shrink-0" style={{ color: getFileIcon(name) }} />
      <span className="text-sm truncate">{name}</span>
    </Button>
  )
}

function highlightCode(code: string, extension: string): string {
  // Clean syntax highlighting similar to VS Code
  const highlighted = code
    // Strings
    .replace(/(".*?")/g, '<span style="color: #ce9178">$1</span>')
    .replace(/('.*?')/g, '<span style="color: #ce9178">$1</span>')
    // Comments
    .replace(/(\/\/.*$)/gm, '<span style="color: #6a9955">$1</span>')
    .replace(/(\/\*[\s\S]*?\*\/)/g, '<span style="color: #6a9955">$1</span>')
    // Keywords
    .replace(
      /\b(import|export|from|interface|type|const|let|var|function|class|extends|implements|return|if|else|for|while|do|switch|case|break|continue|try|catch|finally|throw|new|this|super|static|public|private|protected|readonly|async|await|default)\b/g,
      '<span style="color: #569cd6">$1</span>',
    )
    // Types
    .replace(
      /\b(string|number|boolean|object|any|void|null|undefined|React|useState|useEffect|useRef)\b/g,
      '<span style="color: #4ec9b0">$1</span>',
    )
    // Decorators
    .replace(/(@\w+)/g, '<span style="color: #dcdcaa">$1</span>')
    // Brackets and braces
    .replace(/(\{|\}|\[|\]|\(|\))/g, '<span style="color: #ffd700">$1</span>')
    // JSX tags
    .replace(/(<\/?[\w\s="/.':;#-\/\?]+>)/g, '<span style="color: #92c5f7">$1</span>')

  return highlighted
}
