import HomeNav from "@/components/core/HomeNav"
import TempFooter from "@/components/core/TempFooter"

export default function PrivacyPage() {
    return (
        <div className="min-h-screen bg-black">
            {/* Navigation */}
            <div className="sticky top-0 z-50 px-4 py-2 ">
                <HomeNav currentPage="Home" />
            </div>

            <main className="container mx-auto px-4 py-12 prose prose-invert max-w-4xl prose-headings:text-zinc-100 prose-p:text-zinc-100 prose-li:text-zinc-100 prose-strong:text-zinc-100 prose-a:text-zinc-100">
                <header className="mb-8 not-prose">
                    <h1 className="text-4xl md:text-6xl font-sans font-bold text-zinc-100">
                        Privacy Policy
                    </h1>
                    <p className="text-sm text-zinc-400 mt-3">Last Updated: September 11, 2025</p>
                    <div className="h-px bg-zinc-800 mt-6" />
                </header>

                <section className="space-y-6 text-zinc-100">
                    <p>
                        DevilDev ("we," "us," or "our") operates the website https://devildev.com (the "Site") and provides an AI-powered platform for codebase visualization and analysis (the "Services"). This Privacy Policy explains how we collect, use, disclose, and safeguard your personal information when you use our Services. By accessing or using our Services, you agree to the terms of this Privacy Policy. If you do not agree, please do not use our Services.
                    </p>

                    <h2 className="text-xl font-semibold">1. Introduction</h2>
                    <p>
                        DevilDev ("we," "us," or "our") operates the website https://devildev.com (the "Site") and provides an AI-powered platform for codebase visualization and analysis (the "Services"). This Privacy Policy explains how we collect, use, disclose, and safeguard your personal information when you use our Services. By accessing or using our Services, you agree to the terms of this Privacy Policy. If you do not agree, please do not use our Services.
                    </p>

                    <h2 className="text-xl font-semibold">2. Information We Collect</h2>
                    <p>We collect the following types of information:</p>

                    <p><strong>A. Personal Information</strong></p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li><strong>Account Data:</strong> Name, email address, and payment details.</li>
                        <li><strong>Communication Data:</strong> Messages sent to us via email or contact forms.</li>
                        <li><strong>Technical Data:</strong> IP address, browser type, device information, and usage data (e.g., pages visited, features used).</li>
                    </ul>

                    <p><strong>B. Code and Project Data</strong></p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li><strong>Uploaded Code:</strong> Codebases, files, and architecture diagrams you upload to the Services.</li>
                        <li><strong>AI-Generated Content:</strong> Prompts, analyses, and visualizations generated by our AI models.</li>
                    </ul>

                    <p><strong>C. Automated Collection</strong></p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li><strong>Cookies and Tracking Technologies:</strong> We use cookies to enhance user experience, analyze trends, and track interactions with our Services. You can manage cookies via your browser settings.</li>
                        <li><strong>Log Files:</strong> Information such as IP addresses, browser type, and access times.</li>
                    </ul>

                    <h2 className="text-xl font-semibold">3. How We Use Your Information</h2>
                    <p>We use your information for the following purposes:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>To provide, maintain, and improve our Services (e.g., generating AI prompts and visualizations).</li>
                        <li>To process payments and manage subscriptions.</li>
                        <li>To communicate with you about updates, security alerts, or support requests.</li>
                        <li>To comply with legal obligations and protect our rights.</li>
                    </ul>

                    <h2 className="text-xl font-semibold">4. Legal Basis for Processing (GDPR Compliance)</h2>
                    <p>For users in the European Economic Area (EEA), we process your data based on:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li><strong>Contractual Necessity:</strong> To fulfill our Terms of Service.</li>
                        <li><strong>Consent:</strong> For marketing communications or cookies where required.</li>
                        <li><strong>Legitimate Interests:</strong> To improve our Services and prevent fraud.</li>
                    </ul>

                    <h2 className="text-xl font-semibold">5. Data Sharing and Disclosures</h2>
                    <p>We may share your information with:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        {/* <li><strong>Paddle.com:</strong> Our payment processor, acting as the merchant of record for transactions.</li> */}
                        <li><strong>AI Service Providers:</strong> Third-party AI models (e.g., OpenAI, Claude) for processing code analysis prompts. Note: Code data is anonymized where possible.</li>
                        <li><strong>Legal Authorities:</strong> If required by law or to protect our rights.</li>
                    </ul>
                    <p>We do not sell your personal information to third parties.</p>

                    <h2 className="text-xl font-semibold">6. Security Measures</h2>
                    <p>We implement industry-standard security practices, including:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>Encryption (SSL/TLS) for data in transit and at rest.</li>
                        <li>Regular security audits and access controls.</li>
                        <li>Anonymization of code data used for AI processing.</li>
                    </ul>

                    <h2 className="text-xl font-semibold">7. Your Rights</h2>
                    <p>Depending on your location, you may have the right to:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>Access, correct, or delete your personal information.</li>
                        <li>Opt out of marketing communications.</li>
                        <li>Restrict or object to data processing.</li>
                        <li>Data portability (e.g., request a copy of your data).</li>
                    </ul>
                    <p>
                        To exercise these rights, contact us at [privacy@devildev.com].
                    </p>

                    <h2 className="text-xl font-semibold">8. International Data Transfers</h2>
                    <p>
                        Your data may be processed in countries outside your residence (e.g., the U.S.). We ensure adequate safeguards through:
                    </p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>Standard contractual clauses (GDPR compliance).</li>
                        <li>Privacy Shield principles (where applicable).</li>
                    </ul>

                    <h2 className="text-xl font-semibold">9. Children’s Privacy</h2>
                    <p>
                        Our Services are not intended for users under 13. We do not knowingly collect children’s data. If you believe a child has provided data to us, contact us immediately.
                    </p>

                    <h2 className="text-xl font-semibold">10. Updates to This Policy</h2>
                    <p>
                        We may update this policy periodically. Changes will be posted on this page with an updated "Last Revised" date. Continued use of our Services constitutes acceptance of these changes.
                    </p>

                    <h2 className="text-xl font-semibold">11. Contact Us</h2>
                    <p>
                        For questions about this Privacy Policy or your data, contact us at:
                    </p>
                    <p>
                        <strong>Email:</strong> lakshay@devildev.com
                    </p>
                </section>
                <TempFooter/>
            </main>
        </div>
    )
}