import HomeNav from "@/components/core/HomeNav"
import TempFooter from "@/components/core/TempFooter"

export default function TermsAndConditionsPage() {
    return (
        <div className="min-h-screen bg-black">
            {/* Navigation */}
            <div className="sticky top-0 z-50 px-4 py-2 ">
                <HomeNav currentPage="Home" />
            </div>

            <main className="container mx-auto px-4 py-12 prose prose-invert max-w-4xl prose-headings:text-zinc-100 prose-p:text-zinc-100 prose-li:text-zinc-100 prose-strong:text-zinc-100 prose-a:text-zinc-100">
                <header className="mb-8 not-prose">
                    <h1 className="text-4xl md:text-6xl font-sans font-bold text-zinc-100">
                        Terms of Service
                    </h1>
                    <p className="text-sm text-zinc-400 mt-3">Last Updated: September 11, 2025</p>
                    <div className="h-px bg-zinc-800 mt-6" />
                </header>

                <section className="space-y-6 text-zinc-100">
                    <p>
                        Welcome to DevilDev! These Terms of Service ("Terms," "Agreement") constitute a legally binding agreement between you ("User," "you") and DevilDev ("Company," "we," "us," "our") governing your access to and use of the DevilDev website (the "Site") and the services that allow you to visualize codebases, chat with your code, and generate AI prompts for changes (collectively, the "Services").
                    </p>
                    <p>
                        By accessing or using our Services, you agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, you may not access or use our Services.
                    </p>

                    <h2 className="text-xl font-semibold">1. Acceptance of Terms</h2>
                    <p>
                        By creating an account, accessing, or using our Services, you acknowledge that you have read, understood, and agree to be bound by this Agreement. If you are entering into this Agreement on behalf of a company or other legal entity, you represent that you have the authority to bind such entity to these terms.
                    </p>

                    <h2 className="text-xl font-semibold">2. Definitions</h2>
                    <p>
                        "Content" refers to code, text, data, architecture diagrams, and other materials uploaded to or generated by the Services.
                    </p>
                    <p>
                        "Free Plan" refers to the subscription plan with the features listed on our pricing page.
                    </p>
                    <p>
                        "Pro Plan" refers to the paid subscription plan with the features listed on our pricing page.
                    </p>
                    <p>
                        "User Account" means the account you create to access the Services.
                    </p>

                    <h2 className="text-xl font-semibold">3. User Accounts and Registration</h2>
                    <p>
                        You are responsible for maintaining the confidentiality of your account login information and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.
                    </p>

                    <h2 className="text-xl font-semibold">4. Description of Services and Subscription Plans</h2>
                    <p>
                        DevilDev provides an AI-powered platform for developers to visualize codebases and generate context-aware prompts.
                    </p>
                    <p>
                        <strong>Free Plan:</strong> We offer a Free Plan that allows you to use a limited version of the Services, as detailed on our pricing page (e.g., "Up to 3 Chats," "Only 1 Project").
                    </p>
                    <p>
                        <strong>Pro Plan:</strong> We offer a paid Pro Plan subscription for $10 USD per month, which provides access to additional features and higher usage limits, as detailed on our pricing page (e.g., "Up to 100 Chats," "Up to 5 Projects," "Better LLM models").
                    </p>
                    <p>
                        We reserve the right to modify, suspend, or discontinue any Service plan (including the Free Plan) or any part thereof at any time with or without notice.
                    </p>

                    <h2 className="text-xl font-semibold">5. Payment Terms, Billing, and Renewal (For Pro Plan)</h2>
                    <p>
                        <strong>Fees:</strong> You agree to pay all applicable fees for the Pro Plan as described on our Site. Fees are non-refundable except as required by law or as stated in our Refund Policy below.
                    </p>
                    {/* <p>
                        <strong>Payment Processor:</strong> All payments for the Pro Plan are processed by Paddle.com Market Ltd., our authorized reseller and merchant of record. By providing a payment method, you authorize Paddle to charge all applicable fees to that method.
                    </p> */}
                    <p>
                        <strong>Automatic Renewal:</strong> Your Pro Plan subscription will automatically renew at the end of each billing cycle until you cancel it. You can cancel your subscription at any time through your account settings.
                    </p>

                    <h2 className="text-xl font-semibold">6. Refund Policy</h2>
                    <p>
                        Given the digital nature of our Services, we do not provide refunds or credits for any partial subscription periods or for unused time if you cancel your Pro Plan, unless otherwise required by applicable law.
                    </p>
                    <p>
                        Refunds may be considered on a case-by-case basis at our sole discretion in extenuating circumstances. This does not affect your statutory rights as a consumer.
                    </p>

                    <h2 className="text-xl font-semibold">7. Intellectual Property Rights</h2>
                    <p>
                        <strong>Your Content:</strong> You retain all intellectual property rights in the code and content you upload to the Services. By uploading Content, you grant DevilDev a worldwide, non-exclusive, royalty-free license to use, process, and display that Content solely for the purpose of providing and improving the Services for you.
                    </p>
                    <p>
                        <strong>Our Services:</strong> The DevilDev Services, including all underlying software, algorithms, architecture diagrams generated by our systems, and our proprietary AI models, are the exclusive property of DevilDev and its licensors and are protected by intellectual property laws.
                    </p>

                    <h2 className="text-xl font-semibold">8. Acceptable Use Policy</h2>
                    <p>You agree not to misuse the Services. Prohibited activities include, but are not limited to:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>Uploading any Content that is unlawful, infringing, or malicious.</li>
                        <li>Reverse engineering, decompiling, or attempting to extract the source code of our Services.</li>
                        <li>Accessing the Services in order to build a competitive product or service.</li>
                        <li>Any activity that places an unreasonable load on our infrastructure.</li>
                    </ul>

                    <h2 className="text-xl font-semibold">9. Limitation of Liability</h2>
                    <p>
                        TO THE FULLEST EXTENT PERMITTED BY LAW, DEVILDEV SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICES; (B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICES.
                    </p>

                    <h2 className="text-xl font-semibold">10. Disclaimer</h2>
                    <p>
                        THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT ANY WARRANTIES OF ANY KIND. WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE. THE AI-GENERATED OUTPUTS ARE PROVIDED FOR INFORMATIONAL PURPOSES ONLY AND SHOULD NOT BE RELIED UPON WITHOUT PROFESSIONAL REVIEW AND VALIDATION WITHIN YOUR CODEBASE.
                    </p>
                </section>
            </main>
            <TempFooter/>
        </div>
    )
}